### PR TITLE
Quality (actions, pre-commit) and tests

### PR DESCRIPTION
**Pull request by kaitj**
## Proposed changes

This PR consolidates the changes first introduced in #18, adding quality actions and tasks. Additionally, adds dry-run testing for different flag options, namely to ensure the additional directory flags do not cause any issues for the workflow.

Note that this PR only ensure the dry-runs can pass without issues.

## Types of changes

What types of changes does your code introduce? Put an `x` in the boxes that apply

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionalitiy)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (if none of the other choices apply)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [x] Changes have been tested to ensure that fix is effective or that a feature works.
- [x] Changes pass the unit tests
- [x] Code has been run through the `poe quality` task
- [x] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

### CODE REVIEW

**Review by tkkuehn — APPROVED** [review]
Looks good and the tests run through on my machine

**Comment by tkkuehn** [comment]
Will merge once we get #30 merged into `dry-run`.

**Review by tkkuehn — CHANGES_REQUESTED** [review]
After merging `labelmerge`, the `test_dwi` task fails (in the actions workflow and locally for me).

**Comment by kaitj** [comment]
Should be fixed now in 717fd3a. Was an issue in where it was pulling the subjects from

**Review by tkkuehn — APPROVED** [review]

**Pull request merged**
